### ISSUE TITLE
Email issues

### ISSUE THREAD

**Issue by sollidius** [UserApplePie/UserApplePie-v4#44]
Tried getting the mass mail function to work, but without any luck.
Tried using SMTP info from my email host, but didn't work. Nothing in error logs etc. Also, what do you mean with E-Mail Site Address ?
Then removed it and hoped it would use the php mailer, fixed FQDN error, but still nothing showing up in inbox/spam folder.
Anyone else having this issue? Or how to get more verbose error output?

**Comment by davarravad** [comment]
What service are you using for your email relay?  I tested with my personal server and it worked.  Just had to make sure my ssl cert setting was correct.  It should work with Gmail, but I think there are settings in the Gmail account that have to be enabled.  Not really sure.

**Comment by sollidius** [comment]
I tried it using MXRoute.
However, I think i went wrong with "Authentication type". (I think i entered the TSL/SSL type in stead of AUTH LOGIN).
I now added my domain to sparkpost, and tried and it's working now. (first had a bounce rejection cause i forgot the DKIM). But it's working now.

**Comment by davarravad** [comment]
Good deal.  I had a feeling it was something simple.
