### ISSUE TITLE
Messages not working.

### ISSUE THREAD

**Issue by sollidius** [UserApplePie/UserApplePie-v4#45]
2017-01-27 4:56AM - require_once(/var/www/UAP/V4/app/Plugins/Messages/Views/messages_sidebar.php): failed to open stream: No such file or directory in /var/www/UAP/V4/app/System/Load.php on line 114

I checked, and the folder name is with lowercase V by default. changing this, fixed it.

root@vps:/var/www/UAP/V4/app/Plugins/Messages# ls
Controllers  MessagesVersion.php  Models  views

**Comment by davarravad** [comment]
Were you able to get Messages plugin working?

FYI... MessagesVersion.php is only used by the Admin Panel to make sure the plugin is up to date.

**Comment by sollidius** [comment]
After changing the folder name it shows up and I did receive the mass email messages.
Will check if messages from user to user work as well this afternoon

**Comment by davarravad** [comment]
Updated the git repo to use uppercase Views folder for Messages plugin.
