### ISSUE TITLE
Question: members-only pages

### ISSUE THREAD

**Issue by sollidius** [UserApplePie/UserApplePie-v4#46]
Hey,
Seeing a little lack of some documentation.
How do I add a new page that is only accessible to users when logged in?
I tried adding a .php file in the /Views/Members folder but that doesn't work.
Can you elaborate a bit more on this? :)

Thanks

**Comment by davarravad** [comment]
Sure.  When I get home I will write a tutorial.

**Comment by davarravad** [comment]
I am working on the tutorial now.  Check the docs on the main site.  It will update as I add the data.  Should be done within the hour.

**Comment by davarravad** [comment]
Check out my quick tutorial here: http://userapplepie.com/Docs/BuildingaPage/24

If you want the page to be members only, just use the following code within the Controllers method to check if user is logged in, and if not it will auto redirect them to login page.

```
            /** Check to see if user is logged in **/
            if($data['isLoggedIn'] = $this->auth->isLogged()){
              //** User is logged in - Get their data **/
              $u_id = $this->auth->user_info();
              $data['currentUserData'] = $this->user->getCurrentUserData($u_id);
              $data['isAdmin'] = $this->user->checkIsAdmin($u_id);
            }else{
              /** User Not logged in - kick them out **/
              \Libs\ErrorMessages::push($this->language->get('user_not_logged_in'), 'Login');
            }
```

**Comment by sollidius** [comment]
Cheers :)
This checks if it an user is registered and if he is an admin. Do you also have something that can work with the user groups? 

so if you make like 6 usergroups and a person is member of multiple groups. Something to list all the groups the member belongs to or something to just check if the user is part of a particular group

**Comment by davarravad** [comment]
I did that in the forum I think.  

There is a better way I'm sure.  Lol

**Comment by davarravad** [comment]
In the Auth Library this is how we check for Admin and Mod.  Notice where I used in_array to do this.  

```
      /**
    	 * Check to see if Current User is Admin
       * @param int $where_id (current user's userID)
       * @return boolean (true/false)
    	 */
    	public function checkIsAdmin($where_id){
        /* Get Current User's Groups */
        $user_groups = $this->authorize->getUserGroups($where_id);
        // Make sure user is logged in
        if(!empty($where_id)){
        	// Get user's group status
        	foreach($user_groups as $user_group_data){
        		$cu_groupID[] = $user_group_data->groupID;
        	}
        }else{
          $cu_groupID[] = "0";
        }
        // Set which group(s) are admin (4)
        if(in_array(4,$cu_groupID)){
          // User is Admin
          return true;
        }else{
          // User Not Admin
          return false;
        }
    	}

      /**
    	 * Check to see if Current User is Mod
       * @param int $where_id (current user's userID)
       * @return boolean (true/false)
    	 */
    	public function checkIsMod($where_id){
        /* Get Current User's Groups */
        $user_groups = $this->authorize->getUserGroups($where_id);
        // Make sure user is logged in
        if(!empty($where_id)){
        	// Get user's group status
        	foreach($user_groups as $user_group_data){
        		$cu_groupID[] = $user_group_data->groupID;
        	}
        }else{
          $cu_groupID[] = "0";
        }
        // Set which group(s) are admin (4)
        if(in_array(3,$cu_groupID)){
          // User is Admin
          return true;
        }else{
          // User Not Admin
          return false;
        }
    	}
```

**Comment by davarravad** [comment]
So for multi groups you should be able to do something like this... 

```
if(in_array(array('3', '4', '5'),$cu_groupID)){
          // User is in groups
          return true;
        }else{
          // User Not in groups
          return false;
        }
```

With 3,4,5 being the group IDs

**Comment by sollidius** [comment]
I seem to be stuck at adding new pages
Say I want domain.tld/Dashboard with some more options etc
I added this in /Views/Members
But I think it's missing a route to actually show Dashboard.php
I tried adding it in Routes.php , but it didn't solve it.

What do I add in Routes.php ? 
$routes[] = self::add('Dashboard','Members', 'dashboard');
does that require any additional functions to load dashboard.php ?

**Comment by davarravad** [comment]
What's your controller look like?

**Comment by sollidius** [comment]
i haven't made a seperate controller cause i'm a bit confused.

Can you list the steps to add a new page:

1) upload newpage.php
2) add to...
3) change ...php
4)... 
?

**Comment by davarravad** [comment]
The routes assign which controllers and methods to use.   The controller then loads the models and views assigned to that request.  

http://userapplepie.com/Docs/BuildingaPage/24

I will make a video tutorial when I get home.  I know it's a pain at first to figure out but once you get the hang of everything it's a piece of pie.

**Comment by davarravad** [comment]
I was able to make a video on how to build a page in UAP 4.  Check it out and let me know if it helps.

https://youtu.be/aPiB1Pk4D8w
