### ISSUE TITLE
Email delivery issues

### ISSUE THREAD

**Issue by sollidius** [UserApplePie/UserApplePie-v4#47]
Using sparkpost smtp injection 
The mass mail tool works (Tho as junk, but works).  But on registration, it gets rejected with message: '501 5.5.2 syntax error MAIL FROM'
Note: sparkpost uses starttls

**Comment by sollidius** [comment]
After debugging for a while, I think i found the issue.  #48 
This fixed the email deliverability issue :)

**Comment by davarravad** [comment]
Sweet thanks.
