### ISSUE TITLE
user activation links

### ISSUE THREAD

**Issue by sollidius** [UserApplePie/UserApplePie-v4#52]
apparently they aren't working.

I did see that a friend of mine received the activation link as:
https://domain.tld/Activate/user/<username>/key/<activation_key>
Is this the correct layout even? Can't really find the backend code which checks this.

**Comment by davarravad** [comment]
Yeah that looks correct.  It is located in the Auth Library.

**Comment by sollidius** [comment]
Weird. When they click the link , they get redirected to the 404 page :/

**Comment by davarravad** [comment]
I will look into it when I get home.  I'm sure it's an easy fix.

**Comment by davarravad** [comment]
This was a very easy fix.  I had the routes looking for lowercase activate instead of Activate.  Bug fixed for next release.
