### ISSUE TITLE
Login Issues With Microsoft Edge.

### ISSUE THREAD

**Issue by davarravad** [UserApplePie/UserApplePie-v4#59]
We are having issues logging into UAP4 while using Microsoft Edge. 

When logging in on the local machine it does not correctly handle the cookies.

For example if opened using http://localhost/, http://127.0.0.1, or http://192.168.0.2

However if assigned to a domain address, http://uap4demo.userapplepie.com it works with no issues.

Still trying to solve this issue, however there is not much information out there.

**Comment by JAMESTEL** [comment]
This isn't so much a bug, but a security feature built into Edge.

> Allow localhost loopback: When this feature is enabled, you can use the special loopback address 127.0.0.1, localhost, or your actual local IP address (e.g., 192.168.1.12) in the address bar to access a web service hosted on your computer. When it's disabled, it'll prevent malicious software that may be running on your computer from displaying things like a dangerous phishing site on your web browser.

You can enable localhost loopback via **about:flags**.

**Comment by davarravad** [comment]
Thank you!
