### ISSUE TITLE
Add customisable permissons

### ISSUE THREAD

**Issue by jackttcoms** [UserApplePie/UserApplePie-v4#79]
On the permissions bit would you ever add check-boxes where you say who can do what?

And also add more things in the settings like this bit of code: ` define("MAX_ATTEMPTS", 5);` should be in the admin and also the private messages, can you add a function where we can change the inbox limits in the admin also  `define('MESSAGE_QUOTA_LIMIT','50');  // Inbox and Outbox total Limit`

Thanks

**Comment by davarravad** [comment]
Yes.  Infact we planned on doing that in time.  

The goal is to reduce the Config.php file to be as small as possible.

**Comment by jackttcoms** [comment]
ok wonderful thanks very much! I look forward to the update :)

**Comment by davarravad** [comment]
I just pushed what I was able to get done today.  Got everything I think will be most commonly changed moved to the database and editable via Admin Panel.

I also added a couple small features.

It is not ready for release yet, but your welcome to try it out on your site.

Let me know what you think, and don't forget to backup your current site before replacing files.

**Comment by davarravad** [comment]
Customizable Permissions plus more moved to Admin Panel and pulled from Database.
